sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u _  --password-stdin registry.heroku.com
install:
  - yarn install
script:
  - yarn build
  # build docker images 
  - docker build -t kikoken/api-climate .
  - docker tag kikoken/api-climate registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    docker push kikoken/api-climate;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  branch: master