sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  # install heroku CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - yarn install
script:
  - yarn build
  - docker build -t kikoken/api-climate .

deploy:
  provider: script
  script:
    # create images dockerhub
    docker push kikoken/api-climate;
  branch: master